name: test_integration
description: Integration tests for adhara socket io plugin
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adhara_socket_io:
    path: ../
  adhara_socket_io_example:
    path: ../example
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ^0.12.2
  test: ^1.9.4

flutter:
  uses-material-design: true
