on:
  pull_request:
  push:
    branches:
      - main
      - master
jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: 'Install dependencies'
        run: |
          flutter pub get
          cd test_integration && flutter pub get && cd ..
          cd example && flutter pub get && cd ..
      - run: flutter format --set-exit-if-changed .
      - run: 'flutter analyze --no-pub --no-fatal-infos .'  # suppressing info - deprecated entries fall under info, and CI shouldn't fail if there are any Deprecated APIs

  ios:
    needs: flutter
    strategy:
      matrix:
        device:
          - 'iPhone 11'
      fail-fast: false
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16.0'
      - name: 'List Simulators'
        run: 'xcrun instruments -s'
      - name: 'Start Simulator'
        run: |
          # grep, extract trim `[` and `]` and pick first result, in case there are many
               UUID=$(
               xcrun instruments -s |
               grep "${{ matrix.device }}" |   # Grep device(s) - can expect more than one
               grep -Eo -m1 "\[.*\]" |         # Extract device ID of the first result
               sed -e 's/^\[//' -e 's/\]$//'   # Trimming the square brackets surrounding UUID
               )
               xcrun simctl boot "${UUID:?No Simulator with this name found}"
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: 'Run Flutter Driver tests'
        timeout-minutes: 15
        run: |
          flutter pub get
          sh bin/run_tests.sh

  android:
    needs: flutter
    strategy:
      matrix:
        api-level: [16, 19, 22, 25, 29]
      fail-fast: false
    runs-on: 'macos-latest'
    # ubuntu-latest cannot be used as it is only a docker container, and unfortunately running
    #  hardware acceleration in container is not allowed by android emulator
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16.0'
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: 'Run Flutter Driver tests'
        timeout-minutes: 15
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: |
            /Users/runner/Library/Android/sdk/tools/bin/avdmanager list
            flutter pub get
            sh bin/run_tests.sh
